#!/bin/sh
gnatmake driver
./driver -e types.lst
gcc -c csupport.c

HOST=$(gcc -dumpmachine)

if [ "$HOST" = "i686-pc-mingw32" ]; then
    PHOST=Win32
else
    PHOST=Win64
fi

gnatmake -j6 -XPRJ_HOST=$HOST -gnateDHOST=$PHOST \
    -P runcheck.gpr -largs csupport.o
./runcheck
